{application,percept2_online,
             [{description,"Percept2 Online Visualisation ."},
              {vsn,"1"},
              {modules,[dbg,percept2_online,percept2_online_app,
                        percept2_online_sampling,percept2_online_sup,
                        percept2_online_trace,toppage_handler,ws_handler]},
              {registered,[]},
              {applications,[kernel,stdlib,cowboy]},
              {mod,{percept2_online_app,[]}},
              {env,[]}]}.
